# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/138_7isjjTtuLQUqC0Z2e7sL_yaU5Hkx_
"""

import pandas as pd
import numpy as np

data = pd.DataFrame(columns=["","EUR", "USD", "CHF", "GBP", "JPY", "CAD"])

data[""] =  ["EUR", "USD", "CHF", "GBP", "JPY", "CAD"]
data["EUR"] = [1,1.01,0.98,0.85,138.15,1.31]
data["USD"] = [0.99,1,0.98,0.84,137.33,1.30]
data["CHF"] = [1.02,1.02,1,0.86,140.30,1.33]
data["GBP"] = [1.18,1.19,1.16,1,163.33,1.54]
data["JPY"] = [0.0072,0.0073,0.0071,0.0061,1,0.0094]
data["CAD"] = [0.77,0.77,0.75,0.65,105.86,1]
data.head(20)

from_currency = str(input("Enter in the currency you'd like to convert from: ")).upper()

to_currency = str(input("Enter in the currency you'd like to convert to: ")).upper()

amount = float(input("Enter in the amount of money: "))

x = float(data.loc[data[""]==to_currency][from_currency])
sum = x*amount
sum = "{:,.2f}".format(sum)
amount ="{:,.2f}".format(amount)

print(f"{amount} {from_currency} is {sum} {to_currency}")